In [1]:
import joblib
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [2]:
x_train = joblib.load('../data/processed/x_train.pkl')
y_train = joblib.load('../data/processed/y_train.pkl')
x_test = joblib.load('../data/processed/x_test.pkl')
y_test = joblib.load('../data/processed/y_test.pkl')
x_valid = joblib.load('../data/processed/x_valid.pkl')
y_valid = joblib.load('../data/processed/y_valid.pkl')

In [3]:
print(x_train.shape , y_train.shape)
print(x_test.shape , y_test.shape)
print(x_valid.shape , y_valid.shape)

(43012, 8) (43012,)
(9395, 12) (9395,)
(9394, 12) (9394,)

In [4]:
x_train.describe()

,Temperature,Humidity,TVOC,eCO2,Raw_H2,Raw_Ethanol,Pressure,PM1.0
count,43012.000000,43012.000000,43012.000000,43012.000000,43012.000000,43012.000000,43012.000000,43012.000000
mean,17.412674,51.180581,445.891263,404.748582,13060.146773,19833.352948,939.359203,1.184725
std,9.147209,2.919829,534.418130,14.219722,132.202866,292.925289,0.426407,0.659586
min,-10.490000,41.350000,0.000000,400.000000,12622.000000,19358.000000,937.624000,0.100000
25%,14.790560,48.670000,25.000000,400.000000,12940.750000,19446.000000,938.804000,0.639722
50%,19.328804,51.220000,131.000000,400.000000,13105.000000,19976.000000,939.614544,0.992176
75%,24.520000,53.430000,1134.000000,400.000000,13163.000000,20053.000000,939.662000,1.780000
max,28.910000,61.650000,1490.000000,495.000000,13438.000000,20795.000000,939.856000,3.190000

In [5]:
sc = StandardScaler()
x_train_nr = sc.fit_transform(x_train)

In [6]:
x_train_norm = pd.DataFrame(x_train_nr, columns=x_train.columns)
x_train_norm

,Temperature,Humidity,TVOC,eCO2,Raw_H2,Raw_Ethanol,Pressure,PM1.0
0,1.061246,-1.305085,1.463494,0.017681,-1.143308,-1.383826,-1.480300,0.720573
1,-0.166465,1.177966,-0.834359,-0.333947,0.104789,0.469910,0.909463,-1.311027
2,-2.864806,0.081998,-0.740798,-0.333947,1.299936,1.132203,0.761715,1.508956
3,0.129803,1.301262,-0.243055,-0.333947,0.354408,0.391391,0.065190,-1.250383
4,-1.695583,-0.767376,-0.542449,-0.333947,1.163780,0.804471,0.693704,0.644767
...,...,...,...,...,...,...,...,...
43007,0.078071,-0.662943,-0.813775,-0.333947,0.414922,0.616707,0.708026,-0.885544
43008,-0.240658,0.246169,-0.830616,-0.333947,-0.485220,0.316286,0.872323,-1.359172
43009,1.001100,1.763790,-0.834359,-0.333947,0.278766,0.562085,0.847074,-0.852341
43010,0.217554,0.386814,-0.817518,-0.333947,1.178908,1.115134,0.588170,-0.022325
43011,-0.256038,1.514591,-0.785707,-0.333947,0.240945,0.514291,0.753481,-0.637639

In [7]:
new_cols = ['Temperature', 'Humidity', 'TVOC', 'eCO2', 'Raw_H2', 'Raw_Ethanol', 'Pressure', 'PM1.0']

x_test = x_test[new_cols].copy()
x_valid = x_valid[new_cols].copy()

In [10]:
joblib.dump(x_train, '../data/processed/x_train.pkl')
joblib.dump(x_train_norm, '../data/processed/x_train_norm.pkl')
joblib.dump(y_train, '../data/processed/y_train.pkl')
joblib.dump(x_valid, '../data/processed/x_valid.pkl')
joblib.dump(y_valid, '../data/processed/y_valid.pkl')
joblib.dump(x_test, '../data/processed/x_test.pkl')
joblib.dump(y_test, '../data/processed/y_test.pkl')

['../data/processed/y_test.pkl']

In [11]:
print(x_train.shape , y_train.shape)
print(x_train_norm.shape , y_train.shape)
print(x_test.shape , y_test.shape)
print(x_valid.shape , y_valid.shape)

(43012, 8) (43012,)
(43012, 8) (43012,)
(9395, 8) (9395,)
(9394, 8) (9394,)

> terlihat bahwa data skala nya cukup lebar, solusi awal bs di lakukan standarisasi

> data valid dan test, bs dilakukan remove kolom